version: '3'

tasks:
  build-be: 
    cmds: 
      - docker build -f Pastebin/Dockerfile -t pastebin .
    silent: false

  build-fe:
    cmds: 
      - docker build -f ui/Dockerfile -t pastebin-ui .
    silent: false

  setup-networking:
    cmds:
      - |-
        if ! docker network inspect net >/dev/null 2>&1; then
          docker network create net
        fi
  mongo:
    cmds:
      - |-
        if ! docker ps -a --format '{{.Names}}' | grep -q '^mongodb$'; then
          docker run -d --name mongodb \
          --network net \
          -p 27017:27017 \
          -v mongo_data:/data/db \
          -e MONGO_INITDB_ROOT_USERNAME=admin \
          -e MONGO_INITDB_ROOT_PASSWORD=adminpass \
          mongo:latest
        fi
    silent: false

  be:
    cmds:
      - docker run -d -p 5000:8080 --network net pastebin 
    silent: false

  fe:
    cmds:
      - docker run -d -p 8080:8080 pastebin-ui
    silent: false

  default:
    cmds:
      - task: build-be
      - task: build-fe
      - task: be
      - task: fe
      - task: setup-networking
      - task: mongo

    silent: false

  rebuild:
    cmds:
      - task: build-be
      - task: build-fe
      - task: be
      - task: fe

  rerun:
    cmds:
      - task: be
      - task: fe

    silent: false
