export const DOCS_PER_PAGE      = 50
export const LARGE_FILE_ROWS    = 5000
export const PREVIEW_CAP        = 50
export const DISPLAY_SIZE_LIMIT = 200 * 1024   // 200 KB — large-file threshold
export const DISPLAY_CHARS      = 8000          // chars to show in textarea for large files
export const MAX_FIELD_SAMPLE   = 200           // docs to scan for available fields
export const FILTER_CHUNK_SIZE  = 10000         // docs per async filter chunk
export const SEARCH_DEBOUNCE_MS = 300           // ms debounce for search input
export const SEARCH_MIN_CHARS   = 2             // min search chars for large files
